export const data = [
  {
    id: '0',
    bookName: 'Муми-тролли на рыбалке',
    author: 'Янссон Туве Марика',
    price: '918',
    publishingHouse: 'АСТ',
    quantityInStock: '5',
    image: 'src/assets/img/Янссон-Туве-Марика-Муми-тролли-на-рыбалке.jpeg',
    publicationYear: '2021',
    isPopular: 'Нет',
  },
  {
    id: '1',
    bookName: 'Секреты муми-троллей',
    author: 'Янссон Туве Марика',
    price: '449',
    publishingHouse: 'РОСМЭН',
    quantityInStock: '3',
    image: 'src/assets/img/Янссон-Туве-Марика-Секреты-муми-троллей.jpeg',
    publicationYear: '2021',
    isPopular: 'Да',
  },
  {
    id: '2',
    bookName: 'Муми-тролли и Остров с маяком',
    author: 'Янссон Туве Марика',
    price: '669',
    publishingHouse: 'АСТ',
    quantityInStock: '10',
    image: 'src/assets//img/Янссон-Туве-Марика-Муми-тролли-и-Остров-с-маяком.jpeg',
    publicationYear: '2021',
    isPopular: 'Да',
  },
  {
    id: '3',
    bookName: 'Муми-тролль и песнь океана',
    author: 'Янссон Туве Марика',
    price: '409',
    publishingHouse: 'РОСМЭН',
    quantityInStock: '8',
    image: 'src/assets/img/Янссон-Туве-Марика-Муми-тролль-и-песнь-океана.jpeg',
    publicationYear: '2019',
    isPopular: 'Да',
  },
  {
    id: '4',
    bookName: 'Папа и море',
    author: 'Янссон Туве Марика',
    price: '421',
    publishingHouse: 'Азбука',
    quantityInStock: '16',
    image: 'src/assets/img/Янссон-Туве-Марика-Папа-и-море.jpeg',
    publicationYear: '2021',
    isPopular: 'Да',
  },
  {
    id: '5',
    bookName: 'Зима Муми-тролля',
    author: 'Янссон Туве Марика',
    price: '461',
    publishingHouse: 'Азбука',
    quantityInStock: '2',
    image: 'src/assets/img/Янссон-Туве-Марика-Зима-Муми-тролля.jpeg',
    publicationYear: '2021',
    isPopular: 'Нет',
  },
  {
    id: '6',
    bookName: 'Летняя книга',
    author: 'Янссон Туве Марика',
    price: '240',
    publishingHouse: 'Азбука',
    quantityInStock: '4',
    image: 'src/assets/img/Янссон-Туве-Марика-Летняя-книга.jpeg',
    publicationYear: '2021',
    isPopular: 'Нет',
  },
  {
    id: '7',
    bookName: 'Путешествие налегке',
    author: 'Янссон Туве Марика',
    price: '229',
    publishingHouse: 'Азбука',
    quantityInStock: '9',
    image: 'src/assets/img/Янссон-Туве-Марика-Путешествие-налегке.jpeg',
    publicationYear: '2020',
    isPopular: 'Нет',
  },
];
